language: perl
sudo: false
perl:
  - "5.10"
  - "5.12"
  - "5.16"
  - "5.20"
  - "5.24"

install:
  - cpanm --quiet --installdeps --notest .

script:
  - perl Build.PL
  - ./Build build
  - ./Build test
