environment:
  perl_version: 5.28.0.1

init:
  - git config --global core.autocrlf false

install:
  - ps: Invoke-WebRequest -Uri http://strawberryperl.com/download/$env:perl_version/strawberry-perl-$env:perl_version-64bit.msi -OutFile strawberry-perl.msi
  - ps: Start-Process msiexec.exe -ArgumentList @("/package", "strawberry-perl.msi", "/qn", "INSTALLDIR=C:\strawberry") -Wait
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - appveyor-retry cpanm --notest --quiet Module::Build::XSUtil
  - appveyor-retry cpanm --notest --quiet Carton
  - appveyor-retry carton install --without develop

build: off

test_script:
  - SET PATH=%CD%\local\bin;%PATH%
  - SET PERL5LIB=%CD%\local\lib\perl5;%PERL5LIB%
  - perl Build.PL
  - Build
  - Build test

cache:
  - local

shallow_clone: true
