name = "Hash-Util-Pick"
badges = ["github-actions/test.yml", "metacpan"]
authority = "cpan:PINE"
authors = ["Pine Mizune"]
license = "mit"

module_maker = "ModuleBuild"
markdown_maker = "Pod::Markdown::Github"

[build]
build_class = "builder::MyBuilder"
